services:
  - type: web
    name: radju-bot
    runtime: python
    runtimeVersion: "3.11.9" 

    # Исправлено: принудительно ставим библиотеки при сборке
    buildCommand: pip install "python-telegram-bot[webhooks]==21.10" httpx==0.28.1

    # Исправлено: запускаем напрямую через питон, без gunicorn
    startCommand: python bot.py

    envVars:
      - key: TELEGRAM_TOKEN
        sync: false

      - key: PROXY_API_KEY
        sync: false

      - key: RENDER_EXTERNAL_URL
        sync: false

      - key: PYTHONUNBUFFERED
        value: "1"
